(
    timer access for pijFORTHos
)

BASESAVE HEX

MMIOBASE 3000 + CONSTANT TIMERBASE
TIMERBASE 4 + CONSTANT FREECTRLOW
TIMERBASE 8 + CONSTANT FREECTRHI

DECIMAL

: MSECS 1000 * ;
: SECS 1000000 * ;

: TIME@ FREECTRHI @ FREECTRLOW @ ; ( -- timeh timel )
: TIMEL@ FREECTRLOW @ ;

: WAITUNTIL ( time -- )
    BEGIN
    TIMEL@ OVER >
    UNTIL
;
: WAITFOR ( usecs -- ) TIMEL@ + WAITUNTIL ;

( time -- since )
: TIMESINCE TIMEL@ SWAP - ;

BASERESTORE
